<?php

// $Id$

/**
 * @file
 *
 * Creates new form elements and modifies existing ones to suit for use with the Islandora Form Builder Module.
 * 
 */
module_load_include('inc', 'islandora_form_builder_elements', 'Utilities');
islandora_form_builder_elements_load_all_include_files();

/**
 * Implements hook_elements. Registers Elements.
 * 
 * @return array
 */
function islandora_form_builder_elements_elements() {
  $type['fieldset'] = array(
    '#input' => TRUE,
    '#process' => array('islandora_form_builder_elements_process_fieldset'),
  );
  $type['textfield'] = array(
    '#input' => TRUE,
  );
  $type['textarea'] = array(
    '#input' => TRUE,
  );
  $type['select'] = array(
    '#input' => TRUE,
  );
  $type['set'] = array(
    '#input' => TRUE,
    '#process' => array('islandora_form_builder_elements_process_set'),
  );
  $type['filechooser'] = array(
    '#input' => TRUE,
    '#path' => '',
    '#model' => '',
    '#collection' => '',
    '#process' => array('islandora_form_builder_elements_process_filechooser'),
    '#element_validate' => array('islandora_form_builder_elements_validate_filechooser'),
  );
  $type['datepicker'] = array(
    '#input' => TRUE,
  );
  $type['tabpanel'] = array(
    '#input' => TRUE,
    '#process' => array('islandora_form_builder_elements_process_tabpanel'),
  );
  return $type;
}

/**
 * Implements hook_theme. Register themes.
 *
 * @return array
 */
function islandora_form_builder_elements_theme() {
  return array(
    'filechooser' => array('arguments' => array('element'), 'file' => 'includes/FileChooser.inc'),
    'datepicker' => array('arguments' => array('element'), 'file' => 'includes/DatePicker.inc'),
    'set' => array('arguments' => array('element'), 'file' => 'includes/Set.inc'),
    'tabpanel' => array('arguments' => array('element'), 'file' => 'includes/TabPanel.inc'),
    'tabpanel_items' => array('arguments' => array('form' => NULL, 'element'), 'file' => 'includes/TabPanel.inc'),
  );
}

/**
 * Implements hook_menu. Register menus.
 *
 * @return array 
 */
function islandora_form_builder_elements_menu() {
  module_load_include('inc', 'fedora_repository', 'ObjectHelper');
  $items['formbuilder/elements/ahah/tabpanel'] = array(
    'page callback' => 'islandora_form_builder_elements_ahah_tabpanel',
    'type' => MENU_CALLBACK,
    'access arguments' => array(ObjectHelper::$INGEST_FEDORA_OBJECTS),
    'file' => 'includes/TabPanel.inc',
  );
  $items['autocomplete_marcrelator/%'] = array(
    'title' => 'autocomplete',
    'page callback' => 'islandora_form_builder_elements_autocomplete_marcrelator',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access arguments' => array(ObjectHelper::$INGEST_FEDORA_OBJECTS),
    'file' => 'includes/AutoComplete.inc'
  );
  $items['autocomplete_gacs/%'] = array(
    'title' => 'autocomplete',
    'page callback' => 'islandora_form_builder_elements_autocomplete_gacs',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access arguments' => array(ObjectHelper::$INGEST_FEDORA_OBJECTS),
    'file' => 'includes/AutoComplete.inc'
  );
  $items['autocomplete_language/%'] = array(
    'title' => 'autocomplete',
    'page callback' => 'islandora_form_builder_elements_autocomplete_language',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access arguments' => array(ObjectHelper::$INGEST_FEDORA_OBJECTS),
    'file' => 'includes/AutoComplete.inc'
  );
  $items['autocomplete_person/%'] = array(
    'title' => 'autocomplete',
    'page callback' => 'islandora_form_builder_elements_autocomplete_person',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access arguments' => array(ObjectHelper::$INGEST_FEDORA_OBJECTS),
    'file' => 'includes/AutoComplete.inc'
  );
  $items['autocomplete/%/%'] = array(
    'title' => 'autocomplete',
    'page callback' => 'islandora_form_builder_elements_autocomplete',
    'page arguments' => array(1, 2),
    'type' => MENU_CALLBACK,
    'access arguments' => array(ObjectHelper::$INGEST_FEDORA_OBJECTS),
    'file' => 'includes/AutoComplete.inc',
  );
  $items['filechooser/getThumbnail/%/%/%'] = array(
    'title' => 'getThumbnail',
    'page callback' => 'islandora_form_builder_elements_filechooser_get_thumbnail',
    'page arguments' => array(2, 3, 4),
    'type' => MENU_CALLBACK,
    'access arguments' => array(ObjectHelper::$INGEST_FEDORA_OBJECTS),
    'file' => 'includes/FileChooser.inc'
  );
  $items['filechooser/generatePreview/%/%'] = array(
    'title' => 'generatePreview',
    'page arguments' => array(2, 3),
    'type' => MENU_CALLBACK,
    'access arguments' => array(ObjectHelper::$INGEST_FEDORA_OBJECTS),
    'file' => 'includes/FileChooser.inc'
  );
  return $items;
}

